### ISSUE TITLE
Hardcoded bundle ID in UserDefaults suite name causes defaults to become inaccessible when bundle ID is changed

### ISSUE THREAD

**Issue by rborn** [katagaki/Unagent#7]
Hi, thanks for the extension 🥰

I have some issues with it, it doesn't seem to work.
- I have build it and installed it on the phone (with my own bundleid)
- I have selected a different UA
- I have enabled it in Settings->Safari->Extensions

But it doesn't seem to do anything, if I visit https://my-user-agent.com/ Is till get the default one.

iPhone 12 Pro, iOs 16.6

Any idea? thank you ❤️

**Comment by katagaki** [comment]
@rborn You might want to check the Safari 'Aa' menu (the one on the left side of the address bar) and see if there's an exclamation mark beside Unagent. Tapping that, you should be able to set the right permissions.

After changing settings, you might need to refresh the page another time to see the settings reflected, due to a limitation in how Unagent currently updates user agent settings.

Let me know if that doesn't work, and we can figure it out!

**Comment by rborn** [comment]
nope :(

![IMG_15F2AD58C0D4-1](https://github.com/katagaki/Unagent/assets/406409/d6b21e46-1752-43ee-9380-6654f4d287b7)

**Comment by katagaki** [comment]
Hmm, would you mind sharing your current configuration in the Unagent app?

**Comment by rborn** [comment]
I found this in console:

Extension request contains input items but the extension point does not specify a set of allowed payload classes. The extension point's NSExtensionContext subclass must implement `+_allowedItemPayloadClasses`. This must return the set of allowed NSExtensionItem payload classes. In future, this request will fail with an error.

**Comment by rborn** [comment]
Ok, I found out, you have hardcoded the app bundle id so I had to chanage with mine everywhere ( like here: https://github.com/katagaki/Unagent/blob/main/Extension/SafariWebExtensionHandler.swift#L13C56-L13C56)

Now it works, thank you 🥰

**Comment by katagaki** [comment]
Hmm 🤔
That might be a problem for others forking the repository for this app...
I'll update the code, but if you want to make a PR to fix it, please feel free to!

**Comment by rborn** [comment]
My swift is not so good, but I'll try 😅 On Aug 21, 2023, at 3:59 PM, Justin ***@***.***> wrote:﻿
Hmm 🤔
That might be a problem for others forking the repository for this app...
I'll update the code, but if you want to make a PR to fix it, please feel free to!

**Comment by katagaki** [comment]
@rborn I've gone ahead and pushed the fix for this issue, the bundle IDs should follow a similar format to the below:

Main app: `your.bundle.id`
Extension: `your.bundle.id.Extension`

I'm going to close out this issue for now, but if you face any issues with the new implementation, please feel free to re-open it!

**Comment by rborn** [comment]
Amazing , thank you ❤️
